name:                gsd
version:             0.1.0.0
github:              "smalewski/gsd"
license:             GPL-3
author:              "Stefan Malewski"
maintainer:          "smalewsk@dcc.uchile.cl"
copyright:           "2021 Stefan Malewski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/smalewsk/gsd#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- containers
- megaparsec
- mtl
- parser-combinators
- scientific
- servant
- servant-options
- servant-server
- text
- transformers
- unordered-containers
- vector
- wai
- wai-cors
- wai-extra
- warp
- warp-tls

library:
  source-dirs: src

executables:
  gsd:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gsd
    - cmdargs

tests:
  gsd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gsd
