name: Continous Integration
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache dependencies (Unix)
        uses: actions/cache@v1
        if: matrix.os != 'windows-2019'
        with:
          path: ~/.stack
          key: ${{ runner.os }}-store-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('gsd.cabal') }}

      - name: Build generator
        run:  stack build

      - name: Package generator
        shell: bash
        run: |
          mkdir package
          dir=$(stack path --dist-dir)/build/gsd
          [[ -e "$dir/gsd" ]] && cp "$dir/gsd" package/gsd
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: gsd
          path: package
